name: theme_generator
description: A theme generator for flutter projects.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  # path: ^1.8.0

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.6
  lints: ^2.0.0
